name: Test Suite
on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Environment
      uses: actions/setup-node@v3
    
    - name: Cache Node Modules
    - id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: 'smartbugs-curated/0.4.x/node_modules'
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        cd smartbugs-curated/0.4.x
        npm ci
    - name: Run Tests
      run: |
        cd smartbugs-curated/0.4.x
        npx hardhat test